#!/usr/bin/env bash
# commit-msg-hook.sh — local commit-msg hook: refuse a commit whose MESSAGE
# credits a model or a tool with authoring/reviewing the work.
#
# Install (the repo's hooks are opt-in; git never installs hooks from a clone):
#   git config core.hooksPath .githooks
#   ln -sf ../scripts/commit-msg-hook.sh .githooks/commit-msg
# See CONTRIBUTING.md § Setup. The same three rules run in CI over the pushed
# range (.github/workflows/docs-claims.yml -> scripts/check_commit_messages.sh),
# so skipping the hook delays the failure, it does not avoid it — but by then the
# message may already be public, and unlike a file a message cannot be corrected
# without rewriting every descendant commit. That asymmetry is the whole reason
# this hook exists at the message-writing moment.
#
# Shares ONE pattern definition with the file gate and the CI range gate
# (scripts/ai_attribution_patterns.sh). Fails CLOSED: a missing definitions file
# blocks the commit rather than waving it through on an empty pattern.
set -uo pipefail

MSG_FILE="${1:-}"
if [ -z "$MSG_FILE" ] || [ ! -f "$MSG_FILE" ]; then
  echo "commit-msg: no message file given (\$1) - refusing to pass a check that" >&2
  echo "            never read a message." >&2
  exit 1
fi

ROOT="$(git rev-parse --show-toplevel 2>/dev/null || echo .)"
PATTERNS_FILE="$ROOT/scripts/ai_attribution_patterns.sh"
if [ ! -f "$PATTERNS_FILE" ]; then
  echo "commit-msg: missing $PATTERNS_FILE - cannot check the message; blocking." >&2
  exit 1
fi
# shellcheck source=scripts/ai_attribution_patterns.sh
. "$PATTERNS_FILE"
if [ -z "${PATTERN:-}" ] || [ -z "${PATTERN_CREDIT:-}" ] ||
   [ -z "${PATTERN_COAUTHOR:-}" ] || [ -z "${PATTERN_GENERATED:-}" ]; then
  echo "commit-msg: pattern set is empty - blocking rather than checking nothing." >&2
  exit 1
fi

# Comment lines are what git itself strips before storing the message, so they
# are stripped here too: the editor template and the `# Changes to be committed`
# file list would otherwise flag a commit for a filename it merely touches.
body=$(grep -v '^[[:space:]]*#' "$MSG_FILE")

hits=$(printf '%s\n' "$body" |
       grep -inE -e "$PATTERN" -e "$PATTERN_CREDIT" \
                 -e "$PATTERN_COAUTHOR" -e "$PATTERN_GENERATED")
rc=$?
if [ "$rc" -gt 1 ]; then
  echo "commit-msg: grep failed (rc=$rc) - the check did not run; blocking." >&2
  exit 1
fi
if [ -n "$hits" ]; then
  echo "commit-msg: this message credits a model or a tool - commit blocked." >&2
  printf '%s\n' "$hits" | sed 's/^/    /' >&2
  echo "" >&2
  echo "  Not allowed in a commit message:" >&2
  echo "    * a model/tool name next to audit/review/finding/PR/sweep/scan," >&2
  echo "    * any co-authorship trailer, whatever name follows it (this project" >&2
  echo "      is single-author by policy)," >&2
  echo "    * a 'Generated with' / 'Generated by <tool>' footer." >&2
  echo "  Describe the CHANGE and the evidence, not what produced it: write" >&2
  echo "  'external correctness review finding 2' or 'adversarial audit, HIGH'." >&2
  echo "" >&2
  echo "  Same rules run in CI over the pushed range" >&2
  echo "  (scripts/check_commit_messages.sh), so this cannot be deferred." >&2
  exit 1
fi
exit 0
